### PR TITLE
Remove IClientFactory and caching of TokenClients

### LINKED ISSUE #4: OAuth authenticator failing to get token
```
System.InvalidOperationException: A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
   at System.Threading.Tasks.Task.Dispose(Boolean disposing)
   at ClickView.Client.Authenticator.OAuth.Internal.ClientFactory.DiscoveryClientFactory.Refresh()
   at ClickView.Client.Authenticator.OAuth.Internal.ClientFactory.DiscoveryClientFactory.GetClientsAsync()
   at ClickView.Client.Authenticator.OAuth.Internal.ClientFactory.DiscoveryClientFactory.GetTokenClientAsync()
   at ClickView.Client.Authenticator.OAuth.Authenticators.ClientCredentialsTokenSource.GetAccessTokenAsync()
   at ClickView.Client.Authenticator.OAuth.TokenSource.AccessTokenSource.GetTokensAsync()
   at ClickView.Client.Authenticator.OAuth.OAuthAuthenticator`1.GetTokenAsync()
   at ClickView.Client.Authenticator.OAuth.OAuthAuthenticator`1.AuthenticateAsync(IClientRequest request)
   at ClickView.Client.Core.Http.RestClient.ExecuteAsync[TResponse](BaseRestClientRequest`1 request)

```

### PR DESCRIPTION
**Pull request by MrSmoke**
- Cache just the discovery response (Fixes #4)
- Added our own TokenClient to wrap IdentityModel helpers
- Added HttpClient to options to allow callers to specify their own HttpClient

### CODE REVIEW

File: src/RestClient/Authenticators/OAuth/src/Authenticators/ClientCredentialsTokenSource.cs [hunk 1]
```diff
@@ -2,31 +2,27 @@
...
             _scope = string.Join(" ", scopes);
             _logger = loggerFactory.CreateLogger<ClientCredentialsTokenSource>();
         }
 
         protected override async Task<AccessToken> GetAccessTokenAsync()
         {
-            var tokenClient = await _clientFactory.GetTokenClientAsync().ConfigureAwait(false);
-
-            var response = await tokenClient.RequestClientCredentialsAsync(_scope).ConfigureAwait(false);
+            var response = await _tokenClient.GetClientCredentialsTokenAsync(_scope);
```
Comment (joepour) [inline src/RestClient/Authenticators/OAuth/src/Authenticators/ClientCredentialsTokenSource.cs]: The recommendation is to use `.ConfigureAwait(false)` in libraries as it could be used in a project where there is async context.

Comment (MrSmoke) [reply src/RestClient/Authenticators/OAuth/src/Authenticators/ClientCredentialsTokenSource.cs]: whoops yeah i missed a few. Added them
